title: "300zx Project"
description: "Home for everything that's part of the 300zx Project"
url: "https://300zxproject.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "default"

locale: "en-US"
timezone: "America/Chicago"

logo: "/assets/images/300zx_project_single_scaled.png"
masthead_title: "300zx Project"

paginate: 12
paginate_path: /page:num/

search: true
search_provider: lunr
search_full_content: true
lunr:
  search_within_pages: true

author:
  name: "Landon Jurgens"
  avatar: "/assets/images/Landon.webp"
  bio: "The main instigator of trouble around here."
  location: "Texas"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://300zxproject.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/300zxproject"

twitter:
  username: "300zxproject"

social:
  instagram: "https://www.instagram.com/300zxproject/"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/300zxproject"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/300zxproject/"
    - label: "Printables"
      icon: "fas fa-fw fa-cube"
      url: "https://www.printables.com/@slick666_28413/models"
    - label: "Thingiverse"
      icon: "fas fa-fw fa-shapes"
      url: "https://www.thingiverse.com/Slick666/designs"

formspree:
  contact: "xvownezn"
  sponsor_contact: "xrgynqjn"

google_analytics: "G-XXXXXXXXXX"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XXXXXXXXXX"
    anonymize_ip: false

comments:
  provider: "disqus"
  disqus:
    shortname: "300zxproject-com"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

atom_feed:
  hide: false

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      classes: wide
  - scope:
      path: ""
      type: pages
    values:
      layout: single

