on: [push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check links
      id: link-report
      uses: celinekurpershoek/github-actions-link-checker@master
      with:
        # Required:
        url: 'https://300zxproject.com'
        # optional:
        honorRobotExclusions: false
        ignorePatterns: 'github'

    - name: Create Issue
      if: steps.link-report.outputs.status == 'failure'
      uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
