name: Broken link check
on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.1
        with:
          # Required:
          url: 'https://300zxproject.com'
          # optional:
          honorRobotExclusions: false
          ignorePatterns: 'github,google'
          recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"

  create_issue_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/bad-link-check-template.md


