name: Link Snitch
on: push

jobs:
  build:
    env:
      URL: https://300zxproject.com
      FILENAME: report.yaml
      CONFIG: config.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
