name: Broken link check v2

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile.localpreview
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build --config _config.yml,_config.local.yml

      - name: Link Checker
        id: lychee
        #uses: lycheeverse/lychee-action@v1.8.0
        uses: lycheeverse/lychee-action@v1
        with:
          args: '_site/**/*.html'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue